# Matrik
## Definisi
adalah susunan bilangan berbentuk persegi panjang yang disusun dalam baris dan kolom, biasanya dinotasikan dalam tanda kurung atau kurung siku.

## Jenis-jenis matrik
1.Matrik Persegi\
Seperti namanya matrik persegi memiliki kolom dan baris yang sama
contohnya yaitu matrik 3 x 3

$$
\begin{equation*}
A=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
\end{equation*}
$$

2.Matrik Baris\
Yaitu matrik yang hanya memiliki baris, contohnya

$$
\begin{equation*}
A=
\begin{bmatrix}
1&2&3
\end{bmatrix}
\end{equation*}
$$

3.Matrik kolom\
Yaitu hanya memiliki kolom saja, contohnya

$$
\begin{equation*}
A=
\begin{bmatrix}
1\\
2\\
3
\end{bmatrix}
\end{equation*}
$$

4.Diagonal Matriks Persegi\
Matriks persegi dengan semua entri di luar diagonal utama bernilai nol.Contohnya

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0\\
0&2
\end{bmatrix}
\end{equation*}
$$

5.Matriks Nol\
Matriks dengan semua entri bernilai nol,Contoh:

$$
\begin{equation*}
0=
\begin{bmatrix}
0&0\\
0&0
\end{bmatrix}
\end{equation*}
$$

# Operasi Matrik

## Penjumlahan
Penjumlahan matriks adalah operasi yang dilakukan dengan menjumlahkan elemen-elemen yang bersesuaian dari dua matriks. Agar dua matriks dapat dijumlahkan, syarat utama yang harus dipenuhi adalah kedua matriks harus memiliki ukuran yang sama (jumlah baris dan kolom harus sama).

Contoh soal:

$$
\begin{equation*}
A=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
+ B=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
\end{equation*}
$$

hasilnya adalah:


$$
\begin{equation*}
AB=
\begin{bmatrix}
2&4&6\\
8&10&12\\
14&16&18
\end{bmatrix}
\end{equation*}
$$

In [ ]:
import numpy as np

# Definisi matriks A dan B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Penjumlahan matriks
C = A + B

# Menampilkan hasil
print("Matriks A:\n", A)
print("Matriks B:\n", B)
print("Hasil Penjumlahan (A + B):\n", C)

Matriks A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Hasil Penjumlahan (A + B):
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Perkalian
Perkalian matrik adalah nilai pada matrik yang bisa dihasilkan dengan cara dikalikan-nya tiap baris degan kolom yang memiliki jumlah baris yang sama. Operasi ini melibatkan perkalian elemen-elemen matrik. Untuk melakukan perkalian matrik A dan B, jumlah kolom dalam matrik A harus sama dengan jumlah baris dalam matrik B.

Contoh soal:



$$
\begin{equation*}
A=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
B=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
\end{equation*}
$$



dengan cara setiap baris di kalikan dengan setiap kolom lalu hasil perkalian setiap baris tersebut ditambah dan ini adalah hasil akhirnya
:




$$
\begin{equation*}
AB=
\begin{bmatrix}
30&36&42\\
66&81&96\\
102&126&150
\end{bmatrix}
\end{equation*}
$$

In [ ]:
import numpy as np

# Definisi matriks A dan B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Perkalian Matriks
C = np.dot(A, B)

# Menampilkan hasil
print("Matriks A:\n", A)
print("Matriks B:\n", B)
print("Hasil Perkalian A x B:\n", C)


Matriks A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Hasil Perkalian A x B:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


##sifat penjumlahan
##sifat perkalian
##sifat perkalian skalar

## penyelesaian menggunkan invers matrik,invers di cari menggunakan obe


## Soal

$$
-7x_1-6x_2-12x_3=-33\\
5x_1+5x_2+7x_3=24\\
x_1+4x_3=5
$$

Selesaikan menggunakan invers matrik, kemudian invers dicari menggunakan OBE

Penyelesaian:
1. Tulis dalam bentuk matrik

$$Ax=b$$


$$
\begin{equation*}
A=
\begin{bmatrix}
-7&-6&-12\\
5&5&7\\
1&0&4
\end{bmatrix}
b=
\begin{bmatrix}
-33\\
24\\
5
\end{bmatrix}
\end{equation*}
$$


2. menyusun matrik argumen, menubah bagian kiri menjadi matrtik I segingga bagian kanan berubah menjdi A invers.


$$[A][I]$$


$$
\begin{equation*}
\begin{bmatrix}
-7&-6&-12 |1&0&0\\
5&5&7 |0&1&0\\
1&0&4 |0&0&1
\end{bmatrix}
\end{equation*}
$$

3. bagi baris pertama dengan -7, agar elemen (1,1) menjadi 1

$$
\begin{equation*}
\begin{bmatrix}
1&\frac{6}{7}&-\frac{12}{7} |-\frac{1}{7}&0&0\\
5&5&7 |0&1&0\\
1&0&4 |0&0&1
\end{bmatrix}
\end{equation*}
$$


4. nol kan elemen di bawahnya menggunakan operasi:

$$R_2 <-R_2-5R_1$$
$$R_3 <-R_3-R_1$$



$$
\begin{equation*}
\begin{bmatrix}
1&\frac{6}{7}&-\frac{12}{7} |-\frac{1}{7}&0&0\\
0&\frac{5}{7}&-\frac{13}{7}|\frac{5}{7}&1&0\\
0&-\frac{6}{7}&\frac{16}{7} |\frac{1}{7}&0&1
\end{bmatrix}
\end{equation*}
$$


5. ubah elemen (2,2) menjadi 1, dengan cara baris kedua di bagi 5/7

$$R_2 <-R_2 \times \frac{7}{5}$$

$$
\begin{equation*}
\begin{bmatrix}
1&\frac{6}{7}&-\frac{12}{7} |-\frac{1}{7}&0&0\\
0&1&-\frac{13}{5}|\frac{1}{5}&\frac{7}{5}&0\\
0&-\frac{6}{7}&\frac{16}{7} |\frac{1}{7}&0&1
\end{bmatrix}
\end{equation*}
$$

6. nol kan elemen di atas dan bawah (2,2)
menggunakan operasi:


$$R_1<-R_1-\frac{6}{7}R_2$$
$$R_3<-R_3-\frac{6}{7}R_2$$

$$
\begin{equation*}
\begin{bmatrix}
1 & 0 & \frac{102}{35}|& -\frac{13}{35} & -\frac{6}{5} & 0 \\
0 & 1 & -\frac{13}{5} &|\frac{1}{5} & \frac{7}{5} & 0 \\
0 & 0 & \frac{26}{35} &|\frac{13}{26} & \frac{42}{26} & 1
\end{bmatrix}
\end{equation*}
$$

7. ubah elemen (3,3) menjadi 1, dengan cara baris ketiga dibagi dengan 26/35

$$R_3<-R_3 × \frac{35}{26}$$

$$
\begin{equation*}
\begin{bmatrix}
1 & 0 & \frac{102}{35}|& -\frac{13}{35} & -\frac{6}{5} & 0 \\
0 & 1 & -\frac{13}{5} &|\frac{1}{5} & \frac{7}{5} & 0 \\
0 & 0 & 1 &|\frac{13}{26} & \frac{42}{26} & \frac{35}{26}
\end{bmatrix}
\end{equation*}
$$

8. nol kan elemen diatas (3,3)

$$R_1 <-R_1-\frac{102}{35}R_3$$
$$R_2 <-R_2+\frac{13}{5}R_3$$


dipeoleh inversnya yaitu:

$$
\begin{equation*}
A^{-1} =
\begin{bmatrix}
\frac{26}{35} & \frac{102}{65} & \frac{102}{91} \\
-\frac{7}{5} & \frac{13}{5} & -\frac{35}{26} \\
-\frac{13}{26} & -\frac{42}{26} & \frac{35}{26}
\end{bmatrix}
\end{equation*}
$$

9. kalikan A invers dengan b

$$x=A^{-1}b$$

$$
\begin{equation*}
\begin{bmatrix}
x_1\\
x_2\\
x_3
\end{bmatrix}=
\begin{bmatrix}
\frac{26}{35} & \frac{102}{65} & \frac{102}{91} \\
-\frac{7}{5} & \frac{13}{5} & -\frac{35}{26} \\
-\frac{13}{26} & -\frac{42}{26} & \frac{35}{26}
\end{bmatrix}
\begin{bmatrix}
-33\\
24\\
5
\end{bmatrix}
\end{equation*}
$$

hasil akhirnya adalah

$$x_1=-1, x_2=4, x_3=2$$

## Matriks Determinan
Matriks determinan adalah matriks yang baris dan kolomnyaa samaa. Determinan adalah fungsi yang mengaitkan suatu matriks persegi A dengan sebuah bilangan real (skalar).
Determinan matriks A ditulis sebagai Det(A) atau [A]

 A = $\begin{bmatrix} a & b \\ c & d \end{bmatrix}$ det(A) =ad-bc
 #### contoh:
 A = $\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ det(A) = (1.4)- (2.3)= 4-6= -2

 ### Metode Sarrus (hanya untuk matriks \( A \) berukuran $( 3 \times 3 )$:
 Metode ini hanya berlaku untuk matriks berukuran $ 3\times 3$
 langkah langhkah:
 1. Tuliskan ulang dua kolom pertama di sebelah kanan matriks.
 2. Jumlahkan hasil perkalian diagonal utama, lalu kurangi hasil perkalian diagnal sekunder.
rumus:det( A )=$(\begin{bmatrix} a_{11} & a_{22} & a_{33}+a_{12} & a_{23} & a_{31}+a_{13} & a_{21} & a_{32})-(a_{13} & a_{22} & a_{31}+a_{11} & a_{23} & a_{32}+a_{12} & a_{21} & a_{33}  \end{bmatrix})$
contoh:
A = $\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$

### Sifat sifat Determinan
Sifat penting determinan:
#### 1. Determinan matriks identitas
det( I )= 1, dimana I adalah matriks identitas
#### 2. Baris atau kolom nol
Jika ada baris atau kolom yang semuanya nol, maka det( A )= 0
#### 3. Pertukaran baris/kolom
Jika dua baris atau kolom dipertukarkan, determinan berubah tanda
#### 4. Kelipatan baris/kolom
Jika satu baris atau kolom dikalikan dengan skalar k, maka determinan menjadi k det(A)
 #### 5. Matriks Singular
 Jika det(A) = 0, maka matriks A disebut singular (tidak memimiliki invers)

 ### Apa itu Minor dan Cofaktor?
 *- Minor:* Nilai determinan submatriks yang diperoleh dengan menghapus baris dan kolom tertentu dari matriks.
*- Cofktor*: hasil perka lian minor dengan faktor tanda $(-1)^{i+j}$
dimana i adalah indeks baris dan j adalah indeks kolom.

### Minor matriks
Minor elemen $a_{ij}$, adalah determinan submatriks yang diperoleh dengan menghapus baris ke-i dan kolom ke-j dari matriks asli.
*Contoh:*
Diberikan matriks:
A = $\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$
Minor dari elemen $a_{11}$ adalah:
$N_{11}$= det $\begin{bmatrix} 5 & 6\\ 8 & 9\end{bmatrix} = (5 \cdot 9)-(6 \cdot 8) = 45 - 48 = -3$

### Cofaktor Matriks
Cofaktor elemen $a_{ij}$ adalah hasil perkalian minor $M_{ij}$ dengan faktor tanda $(-1)^{i+j}$.
$C_{ij}= (-1)^{i+j} \cdot M^{i+j}$
*Contoh:*
Menggunakan matriks yang sama:
A = $\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$
Cofaktor dari elemen $a_{11}$ adalah:
$C_{11}= (-1)^{1+1} \cdot M^{11} = 1 \cdot (-3) = -3$
### hubungan Minor dan Cofaktor dengan Determinan
*Peran Minor dan Cofaktor dalam Determinan*
- Determinan matriks dapat dihitung menggunakan ekspansi kofaktor (Laplace Expansion):
- $det(A) = \sum_{j=1}^{n} a_{ij} \cdot c_{ij} \quad$
- atau $det(A) = \sum_{i=1}^{n} a_{ij} \cdot c_{ij} \quad

### Contoh Perhitungan Determinan

#### 1. Contoh Determinan Matriks 3×3
Misalkan diberikan matriks:  
$A =
\begin{bmatrix}
2 & 3 & 1 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}$
Kita gunakan ekspansi kofaktor pada baris pertama:  
$\det(A) = 2
\begin{vmatrix}
5 & 6 \\
8 & 9
\end{vmatrix} - 3
\begin{vmatrix}
4 & 6 \\
7 & 9
\end{vmatrix} + 1
\begin{vmatrix}
4 & 5 \\
7 & 8
\end{vmatrix}$

Hitung determinan dari masing-masing submatriks 2×2:  
$\begin{vmatrix}
5 & 6 \\
8 & 9
\end{vmatrix} = (5 \times 9) - (6 \times 8) = 45 - 48 = -3$

$\begin{vmatrix}
4 & 6 \\
7 & 9
\end{vmatrix} = (4 \times 9) - (6 \times 7) = 36 - 42 = -6$

$\begin{vmatrix}
4 & 5 \\
7 & 8
\end{vmatrix} = (4 \times 8) - (5 \times 7) = 32 - 35 = -3$

Substitusi hasilnya:  
$\det(A) = (2 \times -3) - (3 \times -6) + (1 \times -3)$
$= -6 + 18 - 3 = 9$

#### 2. Contoh Determinan Matriks 4×4  
Misalkan diberikan matriks:  
$B =
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{bmatrix}$
Gunakan ekspansi kofaktor pada baris pertama:  
$\det(B) = 1
\begin{vmatrix}
6 & 7 & 8 \\
10 & 11 & 12 \\
14 & 15 & 16
\end{vmatrix} - 2
\begin{vmatrix}
5 & 7 & 8 \\
9 & 11 & 12 \\
13 & 15 & 16
\end{vmatrix} + 3
\begin{vmatrix}
5 & 6 & 8 \\
9 & 10 & 12 \\
13 & 14 & 16
\end{vmatrix} - 4
\begin{vmatrix}
5 & 6 & 7 \\
9 & 10 & 11 \\
13 & 14 & 15
\end{vmatrix}$

Setiap submatriks 3×3 dihitung dengan metode sebelumnya:  
$\begin{vmatrix}
6 & 7 & 8 \\
10 & 11 & 12 \\
14 & 15 & 16
\end{vmatrix} = (6(11 \times 16 - 12 \times 15)) - (7(10 \times 16 - 12 \times 14)) + (8(10 \times 15 - 11 \times 14))$

$= (6(176 - 180)) - (7(160 - 168)) + (8(150 - 154))$
$= (6 \times -4) - (7 \times -8) + (8 \times -4)$
$= -24 + 56 - 32 = 0$

Karena semua submatriks 3×3 dari ekspansi kofaktor juga bernilai 0, maka:
$\det(B) = 0$


#### 3. Contoh Determinan Matriks 5×5
Misalkan diberikan matriks:
$C =
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 \\
6 & 7 & 8 & 9 & 10 \\
11 & 12 & 13 & 14 & 15 \\
16 & 17 & 18 & 19 & 20 \\
21 & 22 & 23 & 24 & 25
\end{bmatrix}$

Gunakan ekspansi kofaktor pada baris pertama:

$\det(C) =
1 \times C_{11} - 2 \times C_{12} + 3 \times C_{13} - 4 \times C_{14} + 5 \times C_{15}$

di mana $( C_{ij} )$ adalah determinan dari submatriks 4×4 yang diperoleh dengan menghapus baris ke-1 dan kolom ke- $( j )$.
Hitung Submatriks 4×4
Misalkan kita hitung submatriks pertama $( C_{11} )$ dengan menghapus baris pertama dan kolom pertama:

$C_{11} =
\begin{vmatrix}
7 & 8 & 9 & 10 \\
12 & 13 & 14 & 15 \\
17 & 18 & 19 & 20 \\
22 & 23 & 24 & 25
\end{vmatrix}$

Gunakan ekspansi kofaktor pada baris pertama dari $( C_{11} )$:
$\begin{vmatrix}
7 & 8 & 9 & 10 \\
12 & 13 & 14 & 15 \\
17 & 18 & 19 & 20 \\
22 & 23 & 24 & 25
\end{vmatrix} = 7
\begin{vmatrix}
13 & 14 & 15 \\
18 & 19 & 20 \\
23 & 24 & 25
\end{vmatrix} - 8
\begin{vmatrix}
12 & 14 & 15 \\
17 & 19 & 20 \\
22 & 24 & 25
\end{vmatrix} + 9
\begin{vmatrix}
12 & 13 & 15 \\
17 & 18 & 20 \\
22 & 23 & 25
\end{vmatrix} - 10
\begin{vmatrix}
12 & 13 & 14 \\
17 & 18 & 19 \\
22 & 23 & 24
\end{vmatrix}$

Hitung Submatriks 3×3
Misalkan kita hitung determinan submatriks 3×3 pertama:

$\begin{vmatrix}
13 & 14 & 15 \\
18 & 19 & 20 \\
23 & 24 & 25
\end{vmatrix}$

Gunakan ekspansi kofaktor pada baris pertama:

$= 13
\begin{vmatrix}
19 & 20 \\
24 & 25
\end{vmatrix} - 14
\begin{vmatrix}
18 & 20 \\
23 & 25
\end{vmatrix} + 15
\begin{vmatrix}
18 & 19 \\
23 & 24
\end{vmatrix}$

Hitung determinan matriks 2×2:

$\begin{vmatrix}
19 & 20 \\
24 & 25
\end{vmatrix}
= (19 \times 25) - (20 \times 24) = 475 - 480 = -5$

$\begin{vmatrix}
18 & 20 \\
23 & 25
\end{vmatrix}
= (18 \times 25) - (20 \times 23) = 450 - 460 = -10$

$\begin{vmatrix}
18 & 19 \\
23 & 24
\end{vmatrix}
= (18 \times 24) - (19 \times 23) = 432 - 437 = -5$

Substitusi:

$= 13(-5) - 14(-10) + 15(-5)$

$= -65 + 140 - 75 = 0$

Karena semua submatriks 3×3 lainnya memiliki pola angka yang sama, maka determinan semua submatriks 3×3 adalah 0.

Karena setiap submatriks 4×4 memiliki determinan 0, maka:
$\det(C) = 1(0) - 2(0) + 3(0) - 4(0) + 5(0) = 0$

Jadi, determinan matriks 5×5 ini adalah 0