# Matrik
## Definisi
adalah susunan bilangan berbentuk persegi panjang yang disusun dalam baris dan kolom, biasanya dinotasikan dalam tanda kurung atau kurung siku.

## Jenis-jenis matrik
1.Matrik Persegi\
Seperti namanya matrik persegi memiliki kolom dan baris yang sama
contohnya yaitu matrik 3 x 3

$$
\begin{equation*}
A=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
\end{equation*}
$$

2.Matrik Baris\
Yaitu matrik yang hanya memiliki baris, contohnya

$$
\begin{equation*}
A=
\begin{bmatrix}
1&2&3
\end{bmatrix}
\end{equation*}
$$

3.Matrik kolom\
Yaitu hanya memiliki kolom saja, contohnya

$$
\begin{equation*}
A=
\begin{bmatrix}
1\\
2\\
3
\end{bmatrix}
\end{equation*}
$$

4.Diagonal Matriks Persegi\
Matriks persegi dengan semua entri di luar diagonal utama bernilai nol.Contohnya

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0\\
0&2
\end{bmatrix}
\end{equation*}
$$

5.Matriks Nol\
Matriks dengan semua entri bernilai nol,Contoh:

$$
\begin{equation*}
0=
\begin{bmatrix}
0&0\\
0&0
\end{bmatrix}
\end{equation*}
$$

# Operasi Matrik

## Penjumlahan
Penjumlahan matriks adalah operasi yang dilakukan dengan menjumlahkan elemen-elemen yang bersesuaian dari dua matriks. Agar dua matriks dapat dijumlahkan, syarat utama yang harus dipenuhi adalah kedua matriks harus memiliki ukuran yang sama (jumlah baris dan kolom harus sama).

Contoh soal:

$$
\begin{equation*}
A=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
+ B=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
\end{equation*}
$$\
$$
\begin{equation*}
A+B=
\begin{bmatrix}
2&4&6\\
8&10&12\\
14&16&18
\end{bmatrix}
\end{equation*}
$$

In [5]:
import numpy as np

# Definisi matriks A dan B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Penjumlahan matriks
C = A + B

# Menampilkan hasil
print("Matriks A:\n", A)
print("Matriks B:\n", B)
print("Hasil Penjumlahan (A + B):\n", C)

Matriks A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Hasil Penjumlahan (A + B):
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Perkalian
Perkalian matrik adalah nilai pada matrik yang bisa dihasilkan dengan cara dikalikan-nya tiap baris degan kolom yang memiliki jumlah baris yang sama. Operasi ini melibatkan perkalian elemen-elemen matrik. Untuk melakukan perkalian matrik A dan B, jumlah kolom dalam matrik A harus sama dengan jumlah baris dalam matrik B.

Contoh soal:



$$
\begin{equation*}
A=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
B=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
\end{equation*}
$$



dengan cara setiap baris di kalikan dengan setiap kolom lalu hasil perkalian setiap baris tersebut ditambah dan ini adalah hasil akhirnya
:




$$
\begin{equation*}
AB=
\begin{bmatrix}
30&36&42\\
66&81&96\\
102&126&150
\end{bmatrix}
\end{equation*}
$$

In [1]:
import numpy as np

# Definisi matriks A dan B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Perkalian Matriks
C = np.dot(A, B)

# Menampilkan hasil
print("Matriks A:\n", A)
print("Matriks B:\n", B)
print("Hasil Perkalian A x B:\n", C)


Matriks A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Hasil Perkalian A x B:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
