# Matrik
## Definisi
adalah susunan bilangan berbentuk persegi panjang yang disusun dalam baris dan kolom, biasanya dinotasikan dalam tanda kurung atau kurung siku.

## Jenis-jenis matrik
1.Matrik Persegi\
Seperti namanya matrik persegi memiliki kolom dan baris yang sama
contohnya yaitu matrik 3 x 3

$$
\begin{equation*}
A=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
\end{equation*}
$$

2.Matrik Baris\
Yaitu matrik yang hanya memiliki baris, contohnya

$$
\begin{equation*}
A=
\begin{bmatrix}
1&2&3
\end{bmatrix}
\end{equation*}
$$

3.Matrik kolom\
Yaitu hanya memiliki kolom saja, contohnya

$$
\begin{equation*}
A=
\begin{bmatrix}
1\\
2\\
3
\end{bmatrix}
\end{equation*}
$$

4.Diagonal Matriks Persegi\
Matriks persegi dengan semua entri di luar diagonal utama bernilai nol.Contohnya

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0\\
0&2
\end{bmatrix}
\end{equation*}
$$

5.Matriks Nol\
Matriks dengan semua entri bernilai nol,Contoh:

$$
\begin{equation*}
0=
\begin{bmatrix}
0&0\\
0&0
\end{bmatrix}
\end{equation*}
$$

# Operasi Matrik

## Penjumlahan
Penjumlahan matriks adalah operasi yang dilakukan dengan menjumlahkan elemen-elemen yang bersesuaian dari dua matriks. Agar dua matriks dapat dijumlahkan, syarat utama yang harus dipenuhi adalah kedua matriks harus memiliki ukuran yang sama (jumlah baris dan kolom harus sama).

Contoh soal:

$$
\begin{equation*}
A=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
+ B=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
\end{equation*}
$$

hasilnya adalah:


$$
\begin{equation*}
AB=
\begin{bmatrix}
2&4&6\\
8&10&12\\
14&16&18
\end{bmatrix}
\end{equation*}
$$

In [ ]:
import numpy as np

# Definisi matriks A dan B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Penjumlahan matriks
C = A + B

# Menampilkan hasil
print("Matriks A:\n", A)
print("Matriks B:\n", B)
print("Hasil Penjumlahan (A + B):\n", C)

Matriks A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Hasil Penjumlahan (A + B):
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Perkalian
Perkalian matrik adalah nilai pada matrik yang bisa dihasilkan dengan cara dikalikan-nya tiap baris degan kolom yang memiliki jumlah baris yang sama. Operasi ini melibatkan perkalian elemen-elemen matrik. Untuk melakukan perkalian matrik A dan B, jumlah kolom dalam matrik A harus sama dengan jumlah baris dalam matrik B.

Contoh soal:



$$
\begin{equation*}
A=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
B=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
\end{equation*}
$$



dengan cara setiap baris di kalikan dengan setiap kolom lalu hasil perkalian setiap baris tersebut ditambah dan ini adalah hasil akhirnya
:




$$
\begin{equation*}
AB=
\begin{bmatrix}
30&36&42\\
66&81&96\\
102&126&150
\end{bmatrix}
\end{equation*}
$$

In [ ]:
import numpy as np

# Definisi matriks A dan B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Perkalian Matriks
C = np.dot(A, B)

# Menampilkan hasil
print("Matriks A:\n", A)
print("Matriks B:\n", B)
print("Hasil Perkalian A x B:\n", C)


Matriks A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Hasil Perkalian A x B:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


##sifat penjumlahan
##sifat perkalian
##sifat perkalian skalar

## penyelesaian menggunkan invers matrik,invers di cari menggunakan obe


## Soal

$$
-7x_1-6x_2-12x_3=-33\\
5x_1+5x_2+7x_3=24\\
x_1+4x_3=5
$$

Selesaikan menggunakan invers matrik, kemudian invers dicari menggunakan OBE

Penyelesaian:
1. Tulis dalam bentuk matrik

$$Ax=b$$


$$
\begin{equation*}
A=
\begin{bmatrix}
-7&-6&-12\\
5&5&7\\
1&0&4
\end{bmatrix}
b=
\begin{bmatrix}
-33\\
24\\
5
\end{bmatrix}
\end{equation*}
$$


2. menyusun matrik argumen, menubah bagian kiri menjadi matrtik I segingga bagian kanan berubah menjdi A invers.


$$[A][I]$$


$$
\begin{equation*}
\begin{bmatrix}
-7&-6&-12 |1&0&0\\
5&5&7 |0&1&0\\
1&0&4 |0&0&1
\end{bmatrix}
\end{equation*}
$$

3. bagi baris pertama dengan -7, agar elemen (1,1) menjadi 1

$$
\begin{equation*}
\begin{bmatrix}
1&\frac{6}{7}&-\frac{12}{7} |-\frac{1}{7}&0&0\\
5&5&7 |0&1&0\\
1&0&4 |0&0&1
\end{bmatrix}
\end{equation*}
$$


4. nol kan elemen di bawahnya menggunakan operasi:

$$R_2 <-R_2-5R_1$$
$$R_3 <-R_3-R_1$$



$$
\begin{equation*}
\begin{bmatrix}
1&\frac{6}{7}&-\frac{12}{7} |-\frac{1}{7}&0&0\\
0&\frac{5}{7}&-\frac{13}{7}|\frac{5}{7}&1&0\\
0&-\frac{6}{7}&\frac{16}{7} |\frac{1}{7}&0&1
\end{bmatrix}
\end{equation*}
$$


5. ubah elemen (2,2) menjadi 1, dengan cara baris kedua di bagi 5/7

$$R_2 <-R_2 \times \frac{7}{5}$$

$$
\begin{equation*}
\begin{bmatrix}
1&\frac{6}{7}&-\frac{12}{7} |-\frac{1}{7}&0&0\\
0&1&-\frac{13}{5}|\frac{1}{5}&\frac{7}{5}&0\\
0&-\frac{6}{7}&\frac{16}{7} |\frac{1}{7}&0&1
\end{bmatrix}
\end{equation*}
$$

6. nol kan elemen di atas dan bawah (2,2)
menggunakan operasi:


$$R_1<-R_1-\frac{6}{7}R_2$$
$$R_3<-R_3-\frac{6}{7}R_2$$

$$
\begin{equation*}
\begin{bmatrix}
1 & 0 & \frac{102}{35}|& -\frac{13}{35} & -\frac{6}{5} & 0 \\
0 & 1 & -\frac{13}{5} &|\frac{1}{5} & \frac{7}{5} & 0 \\
0 & 0 & \frac{26}{35} &|\frac{13}{26} & \frac{42}{26} & 1
\end{bmatrix}
\end{equation*}
$$

7. ubah elemen (3,3) menjadi 1, dengan cara baris ketiga dibagi dengan 26/35

$$R_3<-R_3 × \frac{35}{26}$$

$$
\begin{equation*}
\begin{bmatrix}
1 & 0 & \frac{102}{35}|& -\frac{13}{35} & -\frac{6}{5} & 0 \\
0 & 1 & -\frac{13}{5} &|\frac{1}{5} & \frac{7}{5} & 0 \\
0 & 0 & 1 &|\frac{13}{26} & \frac{42}{26} & \frac{35}{26}
\end{bmatrix}
\end{equation*}
$$

8. nol kan elemen diatas (3,3)

$$R_1 <-R_1-\frac{102}{35}R_3$$
$$R_2 <-R_2+\frac{13}{5}R_3$$


dipeoleh inversnya yaitu:

$$
\begin{equation*}
A^{-1} =
\begin{bmatrix}
\frac{26}{35} & \frac{102}{65} & \frac{102}{91} \\
-\frac{7}{5} & \frac{13}{5} & -\frac{35}{26} \\
-\frac{13}{26} & -\frac{42}{26} & \frac{35}{26}
\end{bmatrix}
\end{equation*}
$$

9. kalikan A invers dengan b

$$x=A^{-1}b$$

$$
\begin{equation*}
\begin{bmatrix}
x_1\\
x_2\\
x_3
\end{bmatrix}=
\begin{bmatrix}
\frac{26}{35} & \frac{102}{65} & \frac{102}{91} \\
-\frac{7}{5} & \frac{13}{5} & -\frac{35}{26} \\
-\frac{13}{26} & -\frac{42}{26} & \frac{35}{26}
\end{bmatrix}
\begin{bmatrix}
-33\\
24\\
5
\end{bmatrix}
\end{equation*}
$$

hasil akhirnya adalah

$$x_1=-1, x_2=4, x_3=2$$